# Generated by Django 3.1.1 on 2020-10-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('picture', models.ImageField(upload_to='profile_pictures')),
                ('job', models.CharField(max_length=200, null=True)),
                ('arrival_date', models.DateField(auto_now=True)),
                ('extroversion', models.FloatField(default=0.0)),
                ('conscientiousness', models.FloatField(default=0.0)),
                ('neurotism', models.FloatField(default=0.0)),
                ('opening', models.FloatField(default=0.0)),
                ('pleasantness', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
        ),
        migrations.CreateModel(
            name='ConceptCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de concepts',
                'verbose_name_plural': 'Catégories de concepts',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('state', models.CharField(default='starting', max_length=50)),
                ('category', models.ManyToManyField(related_name='contains', to='collaborator.Category')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborator.collaborator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.project')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
            },
        ),
        migrations.CreateModel(
            name='ValueLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_level', models.FloatField(default=0.0)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.value')),
            ],
            options={
                'verbose_name': 'ValueLevel',
                'verbose_name_plural': 'ValueLevels',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.role')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='values',
            field=models.ManyToManyField(related_name='needs', to='collaborator.Value'),
        ),
        migrations.CreateModel(
            name='ExplorationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.concept')),
            ],
            options={
                'verbose_name': "Date d'exploration",
                'verbose_name_plural': "Dates d'exploration",
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='categories',
            field=models.ManyToManyField(related_name='contains', to='collaborator.ConceptCategory'),
        ),
        migrations.AddField(
            model_name='concept',
            name='proxim_concepts',
            field=models.ManyToManyField(related_name='_concept_proxim_concepts_+', to='collaborator.Concept'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='hobbies',
            field=models.ManyToManyField(related_name='hobbies', to='collaborator.Hobby'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='projects',
            field=models.ManyToManyField(related_name='members', through='collaborator.Role', to='collaborator.Project'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='recommended_concepts',
            field=models.ManyToManyField(related_name='pretenders', to='collaborator.Concept'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='skills',
            field=models.ManyToManyField(related_name='can', to='collaborator.Skill'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='value_level',
            field=models.ManyToManyField(related_name='owner', through='collaborator.ValueLevel', to='collaborator.Value'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='visited_concepts_list',
            field=models.ManyToManyField(related_name='explorers', through='collaborator.ExplorationDate', to='collaborator.Concept'),
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_for', to='collaborator.collaborator')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='collaborator.role')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
    ]
