# Generated by Django 3.1.1 on 2020-11-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_auto_20201010_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='collaborator.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='collaborator.company'),
        ),
    ]
