# Generated by Django 3.1.1 on 2020-11-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20201118_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='level',
        ),
    ]
