# Generated by Django 3.1.1 on 2020-11-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0005_remove_value_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.FloatField(default=0.0)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.skill')),
            ],
            options={
                'verbose_name': 'SkillLevel',
                'verbose_name_plural': 'SkillLevels',
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='skill_level',
            field=models.ManyToManyField(related_name='can', through='collaborator.SkillLevel', to='collaborator.Skill'),
        ),
    ]
