# Generated by Django 3.1.1 on 2020-11-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0006_auto_20201119_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'verbose_name': 'Trait de personnalité',
                'verbose_name_plural': 'Traits de personnalité',
            },
        ),
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'verbose_name': 'Niveau de Compétence', 'verbose_name_plural': 'Niveaux de Compétences'},
        ),
        migrations.AlterModelOptions(
            name='valuelevel',
            options={'verbose_name': 'Niveau de Valeur', 'verbose_name_plural': 'Niveaux de Valeurs'},
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='conscientiousness',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='extroversion',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='neurotism',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='pleasantness',
        ),
        migrations.AddField(
            model_name='value',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.CreateModel(
            name='PersonnalityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnality_level', models.FloatField(default=0.0)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('personnality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.personnality')),
            ],
            options={
                'verbose_name': 'Niveau de Trait de personnalité',
                'verbose_name_plural': 'Niveaux de Traits de personnalité',
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='personnality_level',
            field=models.ManyToManyField(related_name='is_caracterised_by', through='collaborator.PersonnalityLevel', to='collaborator.Personnality'),
        ),
    ]
