# Generated by Django 3.1.1 on 2020-11-19 13:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0007_auto_20201119_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='color_field',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
