# Generated by Django 3.1.1 on 2020-11-19 15:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0008_value_color_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='color_field',
        ),
        migrations.AlterField(
            model_name='personnality',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='value',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
