# Generated by Django 3.1.1 on 2020-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0009_auto_20201119_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='deepself_score',
            field=models.FloatField(default=0.0),
        ),
    ]
