# Generated by Django 3.1.1 on 2020-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0010_collaborator_deepself_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
