# Generated by Django 3.1.1 on 2020-11-19 20:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0011_auto_20201119_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('mother_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_skills', to='collaborator.skill')),
            ],
            options={
                'verbose_name': 'Sous-compétence',
                'verbose_name_plural': 'Sous-compétences',
            },
        ),
        migrations.CreateModel(
            name='UnderPersonnality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('mother_personnality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_personnalities', to='collaborator.personnality')),
            ],
            options={
                'verbose_name': 'Sous-trait de personnalité',
                'verbose_name_plural': 'Sous-traits de personnalité',
            },
        ),
    ]
