# Generated by Django 3.1.1 on 2020-11-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0012_underpersonnality_underskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderSkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underskill_level', models.FloatField(default=0.0)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('underskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.underskill')),
            ],
            options={
                'verbose_name': 'Niveau de Sous-compétence',
                'verbose_name_plural': 'Niveaux de Sous-compétences',
            },
        ),
        migrations.CreateModel(
            name='UnderPersonnalityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underpersonnality_level', models.FloatField(default=0.0)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
                ('underpersonnality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.underpersonnality')),
            ],
            options={
                'verbose_name': 'Niveau de Sous-trait de personnalité',
                'verbose_name_plural': 'Niveaux de Sous-traits de personnalité',
            },
        ),
    ]
